name: Build APK S25 Final
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Esta seção abaixo é o que está faltando para parar o erro de 15 segundos
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Preparar Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3-dev libsdl2-dev python3-setuptools libffi-dev libssl-dev
          pip3 install --user --upgrade Cython==0.29.33 buildozer
          export PATH=$PATH:$HOME/.local/bin

      - name: Gerar APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug

      - name: Disponibilizar APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: app-estatisticas-final
          path: bin/*.apk
