name: Build APK Final
on:
  push:
    branches: [ main, principal ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04 # Versão mais estável para o Buildozer

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Buildozer
        run: |
          pip3 install --user buildozer
          pip3 install --user Cython==0.29.33

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # O comando abaixo instala as dependências do Android automaticamente
          buildozer android debug || true 
          # O "|| true" acima impede que ele morra se um aviso bobo aparecer
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
